### ISSUE TITLE
Debugger not shown on some servers with recent session changes

### ISSUE THREAD

**Issue by adrianbj** [nette/tracy#185] opened 2016-05-20 18:05 UTC
Since https://github.com/nette/tracy/commit/5c46e989a61fd2594db6eda0f0da4f904ccad4c7 (all the session changes) I no longer see the debugger bar on one of my servers. I haven't tested widely yet to narrow it down, but here are a few key differences between one that works and one that doesn't.

Works:
PHP 5.6.6
Server API: Apache 2.0 Handler
session.save_handler: files

Doesn't Work:
PHP 5.5.35
Server API: CGI/FastCGI
session.save_handler: user

Let me know if I can provide ant further info.

**Comment by JanTvrdik** [comment] 2016-05-20 19:21
Try following the hint in https://github.com/nette/tracy/issues/154#issuecomment-219694817

**Comment by adrianbj** [comment] 2016-05-20 19:55
Thanks for the tip, but either I am not getting it, or it's still not working. I tried manually doing a: `session_start();`

and also tried adding: `Debugger::dispatch();' after enabling, and still no luck. 

Any chance of some more details on how to actually implement?

Thanks!

**Comment by JanTvrdik** [comment] 2016-05-22 13:41
When using nginx you must use `try_files $uri $uri/ /index.php?$args;` not just `try_files $uri $uri/ /index.php;` otherwise `$_GET` is uninitialized.

**Comment by adrianbj** [comment] 2016-05-22 14:25
Not running nginx - just good ol' apache.

I still have no idea how to get the debug bar to display on this one server.

**Comment by adrianbj** [comment] 2016-05-23 17:18
I have started investigating the problem and I think there are a few things going on. 

1. None of the `$_SESSION['_tracy']['bar']` indexes have any content.
2. If you trigger an error in strict mode so that it is sent to bluescreen, I get the following:

```
?_tracy_bar=content.bdbdc38d34:1 Uncaught SyntaxError: Unexpected token <
```
which actually contains the complete html of the loaded page.

3. triggering an error starts the session, but resets sessions started from other php scripts on the page. In my case this results in me being logged out.

**Comment by adrianbj** [comment] 2016-05-23 17:39
$_GET is empty.

$_SESSION['_tracy'] is:

```
array (2)
bar => array (6)
ba68a5fdc5 => NULL
dd35620d90 => NULL
96011140cc => NULL
240f954a98 => NULL
7cd87a458b => NULL
5095d5b709 => NULL
bluescreen => array (6)
ba68a5fdc5 => NULL
dd35620d90 => NULL
96011140cc => NULL
240f954a98 => NULL
7cd87a458b => NULL
5095d5b709 => NULL
```

Here are the bar resources that are loaded:

![screen shot 2016-05-23 at 10 38 32 am](https://cloud.githubusercontent.com/assets/871211/15478955/91359c94-20d2-11e6-8846-2421e50ac21a.png)

**Comment by adrianbj** [comment] 2016-05-23 17:45
Sometimes the ?_tracy_bar=content resource is not loaded

**Comment by dg** [comment] 2016-05-23 17:51
$_GET is empty on url `?_tracy_bar=content.bdbdc38d34`?

**Comment by adrianbj** [comment] 2016-05-23 18:00
The url has an empty Response when loaded directly with ?_tracy_bar=content.bdbdc38d34. If I remove the _ prefix it loads and the value is displayed in the value of the dumped $_GET

**Comment by adrianbj** [comment] 2016-05-23 18:03
I guess the key thing is that the $_GET['tracy_bar'] is not available inside the dispatchContent() method.

**Comment by dg** [comment] 2016-05-23 18:40
Can you try investigate why your server removes this parameter?

**Comment by adrianbj** [comment] 2016-05-23 19:47
I just figured out a hack to get the debug bar to display. These are the changes I made. 

Basically it is all about getting the $contentId variable that is valid in the render() method into the $session variable in the dispatchContent() method.

I am not suggesting this is the right way to fix it all - it's definitely not, but I think it shows that the only problem is that `$_GET['_tracy_bar']` is not allowing the $session variable to be correctly set.


Bar.php
```
@@ -18,7 +18,7 @@
 
 	/** @var bool */
 	private $dispatched;
-
+	public $contentId;
 
 	/**
 	 * Add custom panel.
@@ -125,14 +125,14 @@
 		require __DIR__ . '/assets/Bar/panels.phtml';
 		require __DIR__ . '/assets/Bar/bar.phtml';
 		$content = Helpers::fixEncoding(ob_get_clean());
-		$contentId = NULL;
+		$this->contentId = NULL;
 
 		if ($this->dispatched) {
-			$contentId = Helpers::isAjax()
+			$this->contentId = Helpers::isAjax()
 				? $_SERVER['HTTP_X_TRACY_AJAX'] . '-ajax'
 				: substr(md5(uniqid('', TRUE)), 0, 10);
 
-			$_SESSION['_tracy']['bar'][$contentId] = ['content' => $content, 'dumps' => $dumps];
+			$_SESSION['_tracy']['bar'][$this->contentId] = ['content' => $content, 'dumps' => $dumps];
 		}
 
 		if (Helpers::isHtmlMode()) {
@@ -185,7 +185,7 @@
 			header('X-Tracy-Ajax: 1'); // session must be already locked
 		}
 		if (preg_match('#^content(-ajax)?.(\w+)$#', isset($_GET['_tracy_bar']) ? $_GET['_tracy_bar'] : '', $m)) {
-			$session = & $_SESSION['_tracy']['bar'][$m[2] . $m[1]];
+			$session = & $_SESSION['_tracy']['bar'][$this->contentId];
 			header('Content-Type: text/javascript');
 			header('Cache-Control: max-age=60');
 			header_remove('Set-Cookie');
@@ -203,4 +203,4 @@
 		}
 	}
```

**Comment by adrianbj** [comment] 2016-05-23 19:58
It seems like there is no call to `?_tracy_bar=content.bdbdc38d34` anymore - it was before, but maybe this is part of the session problem. I guess this is why passes the $contentId through to dispatchContent() is allowing it to working even without that call.

**Comment by adrianbj** [comment] 2016-05-23 20:02
Ok, so I see that the call to `?_tracy_bar=content.bdbdc38d34` won't happen unless $contentId is available to loader.phtml

```
<?php if ($contentId): ?>
<script src="?<?=http_build_query(['_tracy_bar' => "content.$contentId"] + $stopXdebug, NULL, '&amp;')?>"></script>
<?php else: ?>
```

I haven't traced back further than that yet, but I am guessing it will likely be obvious to you now?

**Comment by adrianbj** [comment] 2016-05-23 20:18
Commenting out these line like this also works without any of the changes above because it gets the valid $contentId to loader.phtml:

```
		ob_start(function () {});
		require __DIR__ . '/assets/Bar/panels.phtml';
		require __DIR__ . '/assets/Bar/bar.phtml';
		$content = Helpers::fixEncoding(ob_get_clean());
		//$contentId = NULL;

		/*if ($this->dispatched) {
			$contentId = Helpers::isAjax()
				? $_SERVER['HTTP_X_TRACY_AJAX'] . '-ajax'
				: substr(md5(uniqid('', TRUE)), 0, 10);*/

			$_SESSION['_tracy']['bar'][$contentId] = ['content' => $content, 'dumps' => $dumps];
		//}
```

Hopefully this is helpful and I am not too far removed from the source of the problem.

**Comment by adrianbj** [comment] 2016-05-23 20:36
Apologies - that last post wasn't really true - the $contentId is obviously not set at all, but not setting is what allows the debug bar to show.

**Comment by adrianbj** [comment] 2016-05-23 20:56
Even if I `dump($_GET) inside the `dispatchContent()` method on my local dev setup where the debug bar works fine, it still returns NULL, even though there is a call to `?_tracy_bar=content.dd9018b908` and the debug bar shows. Sorry, I don't think I am being much help at all :)

**Comment by adrianbj** [comment] 2016-05-24 02:58
Sorry for the very fragmented feedback on this - trying to finish up some other things and pack to go on vacation tomorrow.

So it looks like the GET['_tracy_bar'] is there, but it only gets populated the second time `dispatchContent()` is called. I logged it a different way which helped be notice this. I can't see any difference in the behaviour of this on the server that's not working and on my local dev that is working. Back to the $contentId problem?

**Comment by milo** [comment] 2016-05-24 07:23
@adrianbj Could you try to dump `$_SERVER['REQUEST_URI']` when `$_GET` is empty?

**Comment by adrianbj** [comment] 2016-05-24 15:13
Ok, here are the results on this log statement placed just before the `preg_match` in the `dispatchContent()` function. 
```
log($_SERVER['REQUEST_URI']).' : '.json_encode($_GET));
```

**Working Local Dev**
```
2016-05-24 08:04:18	http://pwstable.dev/	"\/" : []
2016-05-24 08:04:21	http://pwstable.dev//-_tracy_bar-content.ef09c91d53/?_tracy_bar=content.ef09c91d53	"\/?_tracy_bar=content.ef09c91d53" : {"_tracy_bar":"content.ef09c91d53"}
```

**Not Working Production Server**
```
2016-05-24 08:11:16	http://sradev.skaharockclimbing.com/	"\/" : []
2016-05-24 08:11:17	http://sradev.skaharockclimbing.com//-_tracy_bar-content.d01560f848/?_tracy_bar=content.d01560f848	"\/?_tracy_bar=content.d01560f848" : {"_tracy_bar":"content.d01560f848"}
```

So I don't think there is any difference and I don't think the issue is related to `$_GET['_tracy_bar']`

**Comment by dg** [comment] 2016-06-08 14:20
I would like to release stable next week. Do you found any reason why it does not work? What about last dev version?

**Comment by adrianbj** [comment] 2016-06-10 19:55
In the latest dev version the debug bar works fine for normal loading if I make just this one change in loader.phtml
```
<?php if ($contentId): ?>
```
to:
```
<?php if (!$contentId): ?>
```

However it still doesn't show the AJAX version of the bar. This https://github.com/nette/tracy/blob/1503008169fe84d8708eede2b2bfae5175019e6d/src/Tracy/Bar.php#L64 is being triggered and `$this->dispatched` is returning TRUE

**Comment by adrianbj** [comment] 2016-06-10 20:43
Just going to keep adding more things as I notice them. Obviously add the `!` like I did above prevents the:
```
http://sradev.skaharockclimbing.com/admin/page/?_tracy_bar=content-ajax.df463f62a9&XDEBUG_SESSION_STOP=1&XDEBUG_PROFILE=0&XDEBUG_TRACE=0&v=0.9820714200674963
```
links from being created.

So, this approach allows that:

```
<?php if ($contentId): ?>
<script src="?<?=http_build_query(['_tracy_bar' => "content.$contentId"] + $stopXdebug, NULL, '&amp;')?>"></script>
<?php endif ?>
<script>
Tracy.Debug.init(<?= json_encode($content) ?>, <?= json_encode($dumps) ?>);
</script>
```

This means that Debug is initiated regardless of $contentId. AJAX calls still don't work though.

**Comment by adrianbj** [comment] 2016-06-11 02:25
Ok, I am very confused. I have access to my local dev environment, a dedicated self managed server (where I host most of my sites), and two separate shared hosts. The latest dev version works on my local dev environment and the self managed server, but not on the shared hosts. On the shared hosts I have changed PHP versions, session settings and some other stuff with no luck.

Have you tested on a basic shared host?

**Comment by adrianbj** [comment] 2016-06-11 02:33
Actually, it might come back to this:

session.save_handler: files vs session.save_handler: user

OR:

Server API: Apache 2.0 Handler vs Server API: CGI/FastCGI

because my dedicated production server matches my dev environment for both of these settings.

I am not very experienced with shared hosting - I have always been lucky to manage my own servers, but these two settings are the same on the problematic shared hosts.

Any thoughts on this?

**Comment by JanTvrdik** [comment] 2016-06-11 09:55
It's quite possible that the custom session save handler is not implemented properly.

**Comment by dg** [comment] 2016-06-11 16:58
@adrianbj can you try to put `session_write_close()` before https://github.com/nette/tracy/blob/587cced3422943a72eee94dcf5c4bcd5ff9f5aab/src/Tracy/Bar.php#L99 ?

**Comment by adrianbj** [comment] 2016-06-11 17:28
Sorry @dg - still no luck with `session_write_close()`

**Comment by dg** [comment] 2016-06-11 17:32
Can you create for me account on this host?

**Comment by adrianbj** [comment] 2016-06-11 18:22
> Can you create for me account on this host?

Email with access details sent.

**Comment by dg** [comment] 2016-06-11 21:47
@adrianbj So I know where the problem is!

Session is closed earlier than bar si rendered. Probably there is `session_write_close` somewhere in your code. 

I tried to re-open session in Bar.php, but it throws PDOException with message `1406 Data too long for column 'data' at row 1'` in `SessionHandlerDB/SessionHandlerDB.module:109`.

It should be fixed now, but you need to discover why session is closed in order to see AJAX requests.

**Closed** 2016-06-11 21:46 UTC

**Comment by adrianbj** [comment] 2016-06-12 21:53
Thanks @dg - I really appreciate you taking a look - your discovery helped me figure out the difference between the servers that work and those that don't. Turns out that on the ones that don't work I was using a module that stores session info in the database, rather than the filesystem. If this is disabled, then it immediately works as expected with AJAX requests.

The data too long error can be fixed by changing the field from text to longtext, but then I end up with:
```
SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes'
```
Changing my max_allowed_packet setting prevents the error, but AJAX requests are still not working. I guess that is still related to the session being closed.

Hopefully this is something that can be fixed on my end, but I'll let you know if there is anything I think could be changed in Tracy to help, short of doing things the old way (ie before https://github.com/nette/tracy/commit/5c46e989a61fd2594db6eda0f0da4f904ccad4c7).

**Comment by adrianbj** [comment] 2016-07-01 21:42
I just wanted to add one final followup that might be useful for others that come across this problem. I now have Tracy reporting AJAX requests even with the database session handler. The key was actually to call `Debugger::shutdownHandler()` before my main script finished and closed its session. So far everything seems to be working using this approach.
